# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(270, 320)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(u"background-color:rgb(100,100, 100);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.textbox = QLineEdit(self.centralwidget)
        self.textbox.setObjectName(u"textbox")
        self.textbox.setGeometry(QRect(10, 5, 250, 41))
        font = QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.textbox.setFont(font)
        self.textbox.setStyleSheet(u"background-color:rgb(170,170, 170);")
        self.textbox.setReadOnly(False)
        self.sum = QPushButton(self.centralwidget)
        self.sum.setObjectName(u"sum")
        self.sum.setGeometry(QRect(210, 140, 48, 48))
        font1 = QFont()
        font1.setPointSize(40)
        self.sum.setFont(font1)
        self.sum.setStyleSheet(u"background-color:rgb(150,150, 150);")
        self.sub = QPushButton(self.centralwidget)
        self.sub.setObjectName(u"sub")
        self.sub.setGeometry(QRect(210, 190, 48, 48))
        self.sub.setFont(font1)
        self.sub.setMouseTracking(False)
        self.sub.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.sub.setLayoutDirection(Qt.LeftToRight)
        self.sub.setStyleSheet(u"background-color:rgb(150,150, 150);")
        self.equal = QPushButton(self.centralwidget)
        self.equal.setObjectName(u"equal")
        self.equal.setGeometry(QRect(210, 240, 48, 48))
        font2 = QFont()
        font2.setPointSize(40)
        font2.setBold(False)
        self.equal.setFont(font2)
        self.equal.setStyleSheet(u"background-color:rgb(160,160, 160);")
        self.AC = QPushButton(self.centralwidget)
        self.AC.setObjectName(u"AC")
        self.AC.setGeometry(QRect(210, 90, 48, 48))
        font3 = QFont()
        font3.setPointSize(18)
        font3.setBold(False)
        self.AC.setFont(font3)
        self.AC.setStyleSheet(u"background-color:rgb(150,150, 150);")
        self.mul = QPushButton(self.centralwidget)
        self.mul.setObjectName(u"mul")
        self.mul.setGeometry(QRect(160, 140, 48, 48))
        self.mul.setFont(font1)
        self.mul.setMouseTracking(False)
        self.mul.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.mul.setLayoutDirection(Qt.LeftToRight)
        self.mul.setStyleSheet(u"background-color:rgb(150,150, 150);")
        self.dev = QPushButton(self.centralwidget)
        self.dev.setObjectName(u"dev")
        self.dev.setGeometry(QRect(160, 190, 48, 48))
        self.dev.setFont(font1)
        self.dev.setStyleSheet(u"background-color:rgb(150,150, 150);")
        self.percent = QPushButton(self.centralwidget)
        self.percent.setObjectName(u"percent")
        self.percent.setGeometry(QRect(160, 240, 48, 48))
        font4 = QFont()
        font4.setPointSize(30)
        font4.setBold(False)
        self.percent.setFont(font4)
        self.percent.setStyleSheet(u"background-color:rgb(150,150, 150);")
        self.PN = QPushButton(self.centralwidget)
        self.PN.setObjectName(u"PN")
        self.PN.setGeometry(QRect(10, 240, 48, 48))
        self.PN.setFont(font)
        self.PN.setStyleSheet(u"background-color:rgb(150,150, 150);")
        self.dot = QPushButton(self.centralwidget)
        self.dot.setObjectName(u"dot")
        self.dot.setGeometry(QRect(110, 240, 48, 48))
        font5 = QFont()
        font5.setPointSize(30)
        font5.setBold(True)
        self.dot.setFont(font5)
        self.dot.setStyleSheet(u"background-color:rgb(150,150, 150);")
        self.n1 = QPushButton(self.centralwidget)
        self.n1.setObjectName(u"n1")
        self.n1.setGeometry(QRect(10, 90, 48, 48))
        self.n1.setFont(font5)
        self.n1.setStyleSheet(u"background-color:rgb(120,120, 120);")
        self.n2 = QPushButton(self.centralwidget)
        self.n2.setObjectName(u"n2")
        self.n2.setGeometry(QRect(60, 90, 48, 48))
        self.n2.setFont(font5)
        self.n2.setStyleSheet(u"background-color:rgb(120,120, 120);")
        self.n3 = QPushButton(self.centralwidget)
        self.n3.setObjectName(u"n3")
        self.n3.setGeometry(QRect(110, 90, 48, 48))
        self.n3.setFont(font5)
        self.n3.setStyleSheet(u"background-color:rgb(120,120, 120);")
        self.n4 = QPushButton(self.centralwidget)
        self.n4.setObjectName(u"n4")
        self.n4.setGeometry(QRect(10, 140, 48, 48))
        self.n4.setFont(font5)
        self.n4.setStyleSheet(u"background-color:rgb(120,120, 120);")
        self.n5 = QPushButton(self.centralwidget)
        self.n5.setObjectName(u"n5")
        self.n5.setGeometry(QRect(60, 140, 48, 48))
        self.n5.setFont(font5)
        self.n5.setStyleSheet(u"background-color:rgb(120,120, 120);")
        self.n6 = QPushButton(self.centralwidget)
        self.n6.setObjectName(u"n6")
        self.n6.setGeometry(QRect(110, 140, 48, 48))
        self.n6.setFont(font5)
        self.n6.setStyleSheet(u"background-color:rgb(120,120, 120);")
        self.n7 = QPushButton(self.centralwidget)
        self.n7.setObjectName(u"n7")
        self.n7.setGeometry(QRect(10, 190, 48, 48))
        self.n7.setFont(font5)
        self.n7.setStyleSheet(u"background-color:rgb(120,120, 120);")
        self.n8 = QPushButton(self.centralwidget)
        self.n8.setObjectName(u"n8")
        self.n8.setGeometry(QRect(60, 190, 48, 48))
        self.n8.setFont(font5)
        self.n8.setStyleSheet(u"background-color:rgb(120,120, 120);")
        self.n9 = QPushButton(self.centralwidget)
        self.n9.setObjectName(u"n9")
        self.n9.setGeometry(QRect(110, 190, 48, 48))
        self.n9.setFont(font5)
        self.n9.setStyleSheet(u"background-color:rgb(120,120, 120);")
        self.n0 = QPushButton(self.centralwidget)
        self.n0.setObjectName(u"n0")
        self.n0.setGeometry(QRect(60, 240, 48, 48))
        self.n0.setFont(font5)
        self.n0.setStyleSheet(u"background-color:rgb(120,120, 120);")
        self.sin = QPushButton(self.centralwidget)
        self.sin.setObjectName(u"sin")
        self.sin.setGeometry(QRect(10, 50, 48, 38))
        font6 = QFont()
        font6.setPointSize(20)
        font6.setBold(False)
        self.sin.setFont(font6)
        self.sin.setStyleSheet(u"background-color:rgb(150,150, 150);")
        self.cos = QPushButton(self.centralwidget)
        self.cos.setObjectName(u"cos")
        self.cos.setGeometry(QRect(60, 50, 48, 38))
        self.cos.setFont(font6)
        self.cos.setStyleSheet(u"background-color:rgb(150,150, 150);")
        self.tan = QPushButton(self.centralwidget)
        self.tan.setObjectName(u"tan")
        self.tan.setGeometry(QRect(110, 50, 48, 38))
        self.tan.setFont(font6)
        self.tan.setStyleSheet(u"background-color:rgb(150,150, 150);")
        self.cot = QPushButton(self.centralwidget)
        self.cot.setObjectName(u"cot")
        self.cot.setGeometry(QRect(160, 50, 48, 38))
        self.cot.setFont(font6)
        self.cot.setStyleSheet(u"background-color:rgb(150,150, 150);")
        self.log = QPushButton(self.centralwidget)
        self.log.setObjectName(u"log")
        self.log.setGeometry(QRect(210, 50, 48, 38))
        self.log.setFont(font6)
        self.log.setStyleSheet(u"background-color:rgb(150,150, 150);")
        self.sqrt = QPushButton(self.centralwidget)
        self.sqrt.setObjectName(u"sqrt")
        self.sqrt.setGeometry(QRect(160, 90, 48, 48))
        self.sqrt.setFont(font3)
        self.sqrt.setStyleSheet(u"background-color:rgb(150,150, 150);")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 270, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Calculator", None))
        self.textbox.setText("")
        self.sum.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.sub.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.equal.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.AC.setText(QCoreApplication.translate("MainWindow", u"AC", None))
        self.mul.setText(QCoreApplication.translate("MainWindow", u"\u00d7", None))
        self.dev.setText(QCoreApplication.translate("MainWindow", u"\u00f7", None))
        self.percent.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.PN.setText(QCoreApplication.translate("MainWindow", u"+/-", None))
        self.dot.setText(QCoreApplication.translate("MainWindow", u".", None))
        self.n1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.n2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.n3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.n4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.n5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.n6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.n7.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.n8.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.n9.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.n0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.sin.setText(QCoreApplication.translate("MainWindow", u"sin", None))
        self.cos.setText(QCoreApplication.translate("MainWindow", u"cos", None))
        self.tan.setText(QCoreApplication.translate("MainWindow", u"tan", None))
        self.cot.setText(QCoreApplication.translate("MainWindow", u"cot", None))
        self.log.setText(QCoreApplication.translate("MainWindow", u"log", None))
        self.sqrt.setText(QCoreApplication.translate("MainWindow", u"sqrt", None))
    # retranslateUi

